version: '3.8'

services:
  django:
    image: django
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      PYTHONUNBUFFERED: "1"
    ports:
      - "8000:8000"
    volumes:
      - ./distributed_storage:/app
    depends_on:
      - minio1
      - minio2

  minio1:
    image: minio/minio
    ports:
      - "9010:9000"
      - "9011:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    volumes:
      - minio1_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio2:
    image: minio/minio
    ports:
      - "9020:9000"
      - "9021:9001"
    environment:
      MINIO_ROOT_USER: minioadmin2
      MINIO_ROOT_PASSWORD: minioadmin2
    command: server --console-address ":9001" /data
    volumes:
      - minio2_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio1_data:
  minio2_data: