# Generated by Django 5.1.5 on 2025-03-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemetadata',
            name='file_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
