# Generated by Django 5.1.5 on 2025-03-17 21:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_filemetadata_nodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=50, unique=True)),
                ('endpoint_url', models.URLField()),
                ('status', models.CharField(default='inactive', max_length=20)),
                ('current_load', models.BigIntegerField(default=0)),
                ('last_heartbeat', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='filemetadata',
            name='nodes',
        ),
        migrations.RemoveField(
            model_name='filemetadata',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='filemetadata',
            name='chunk_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='filemetadata',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='filemetadata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='filemetadata',
            name='file_hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='filemetadata',
            name='file_url',
            field=models.URLField(),
        ),
        migrations.CreateModel(
            name='ChunkMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('chunk_hash', models.CharField(max_length=64)),
                ('chunk_size', models.BigIntegerField()),
                ('node_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.filemetadata')),
            ],
            options={
                'unique_together': {('file', 'chunk_index', 'node_id')},
            },
        ),
    ]
