# Generated by Django 3.2.25 on 2025-03-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_nodemetadata_remove_filemetadata_nodes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemetadata',
            name='is_compressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filemetadata',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='filemetadata',
            name='chunk_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='filemetadata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
