# Generated by Django 3.2.25 on 2025-03-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_auto_20250319_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemetadata',
            name='original_file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
