# Generated by Django 3.2.25 on 2025-03-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_filemetadata_original_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemetadata',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
